### ISSUE TITLE
Context from skygear-server is `undefined`

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-SDK-JS#323]
Using this code

```
skygearCloud.handler('ping', req => 'Hello, world\n', {
  method: ['GET'],
  userRequired: false
})
```

- Skygear SDK Date/Version: 27 Oct, skygear 1.1.0 on portal.skygear.io
- JS runtime: skygear 1.1.0 in package.json
- Skygear Server Date/Version: 
- [ ] Is this a regression?
- [ ] Attached logs, screenshots

#### Actual Results

```
TypeError: Cannot read property 'user_id' of undefined
    at containerFromContext (/usr/src/node_modules/skygear/node_modules/skygear-core/dist/cloud/transport/common.js:87:23)
    at HTTPTransport.handlerHandler (/usr/src/node_modules/skygear/node_modules/skygear-core/dist/cloud/transport/common.js:471:20)
    at HTTPTransport.dispatch (/usr/src/node_modules/skygear/node_modules/skygear-core/dist/cloud/transport/http.js:130:24)
    at IncomingMessage.<anonymous> (/usr/src/node_modules/skygear/node_modules/skygear-core/dist/cloud/transport/http.js:110:18)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

#### Steps to reproduce

1.
2.
3.

**Comment by cheungpat** [comment]
I suspect that the context is undefined because the server omitted the field when the map (dict) is empty (`omitempty`). Will make a fix for this. Thanks for reporting this.
